#!/bin/bash

dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Play
cmd="xset dpms force on && loginctl unlock-session"
sh -c 'xset dpms force on && loginctl unlock-session'
